# Generated by Django 5.0 on 2024-01-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_options_people_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
