# Generated by Django 5.0 on 2024-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опусбликовано')], default=0),
        ),
    ]
