# Generated by Django 5.0 on 2024-01-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_categories_people_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.categories'),
        ),
    ]
