# Generated by Django 5.0 on 2024-01-05 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_partner_alter_people_is_published_people_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-time_create',), 'verbose_name': 'Известные люди', 'verbose_name_plural': 'Известные люди'},
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxValueValidator(100, message='Максимум 100 символов')], verbose_name='Slug'),
        ),
    ]
