# Generated by Django 5.0 on 2024-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_people_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
